### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by muspelheim**
replace to current version symfony and check all urls

### CODE REVIEW

**Comment by tabbabi** [comment]
The SensioLabs Symfony Certification exam is based on the default Symfony Standard Edition package and the Symfony 2.3 LTS version.

**Comment by jmolivas** [comment]
@tabbabi: Exactly the exam is based on the 2.3 LTS version this is the reason the links point to that version. @muspelheim

**Comment by handosensei** [comment]
The SensioLabs Symfony Certification exam is based on version 2.3 or 3.0. 
So when version 3.1 will publish, the change maybe wrong

**Comment by muspelheim** [comment]
@tabbabi ping

**Comment by tautrimas** [comment]
This repository is a top hit in Google in various queries. This PR should definitely be merged and is now very valid as 2.3 is increasingly fading away.

**Pull request closed without merging**
